_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

#_configurator:
#    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
#    prefix:   /_configurator

#_main:
#    resource: routing.yml

_oncall_admin:
    resource: "@OnCallAdminBundle/Resources/config/routing.yml"
    prefix: /

#_user_bundle:
#    resource: "@OnCallUserBundle/Resources/config/routing.yml"
